version: '3'

services:
  # The gateway proxy container
  proxy:
    build:
      context: ./.docker/prod/proxy
      dockerfile: Dockerfile
#    volumes:
#      - ./.docker/prod/certbot/ssl:/etc/nginx/ssl:ro
#      - ./.docker/prod/certbot/acme-challenge:/var/www/acme-challenge:ro
    ports:
      - "443:443"
      - "80:80"
    networks:
      - api
      - client
    restart: unless-stopped

#  # The certbot container
#  certbot:
#    build:
#      context: docker/prod/certbot/app
#      dockerfile: Dockerfile
#    volumes:
#      - ./.docker/prod/certbot/acme-challenge:/var/www/acme-challenge:rw
#      - ./.docker/prod/certbot/ssl:/etc/letsencrypt:rw
#    restart: unless-stopped

networks:
  api:
    external:
      name: api

  client:
    external:
      name: client
