version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./.docker/prod/app/Dockerfile
    hostname: client
    networks:
      - client
      - gateway
    restart: unless-stopped

networks:
  client:
    name: client

  gateway:
    name: gateway
    external: true
